services:
  dev-agent:
    container_name: dev-agent
    build:
      context: .
      args:
        USERNAME: paul
    user: "paul"
    volumes:
      - /Users/paul/code:/workspace
      - /run/host-services/ssh-auth.sock:/run/host-services/ssh-auth.sock
      - ./data/certs:/usr/local/share/ca-certificates/extra:ro
      - ${HOME}/.ssh/id_signing.pub:${HOME}/.ssh/id_signing.pub:ro
    environment:
      - SSH_AUTH_SOCK=/run/host-services/ssh-auth.sock
    command: >
      sh -c "sudo chmod 777 /run/host-services/ssh-auth.sock && sudo update-ca-certificates && sleep infinity"
    restart: always
